[project]

name = "astaire"
version = "0.0.1"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies.syncbox]
git = "https://github.com/carllerche/syncbox"

[[test]]
name = "astaire-test"
path = "test/test.rs"
